language: node_js
sudo: false
node_js:
- '10.16'
install:
- cd public
- npm install
script:
- npm test
before_deploy: cd ..
deploy:
  provider: firebase
  token:
    secure: ND4thoqL3kgwIIJjdV118O7ZVk7cDSyoMgJL+fWnC5ao4APsBsmEvOWDDjAac8QSjWz8UzDY7De85M1YPARYdLUyihxN6F9QKQbrOEZrWWWhj+P/kF1YBqSBnIL6tyfUw8g2rGc7jkxRL2XPqTkqj3vJ2oRvPeu8leDzk8zl/5XyMF5ZP6n9gMJKIcvmldQjcSs96AgJGuy9+17pHMoSbhrm/Dbb2E6RlPnrssUhSfCjPI+Td3uDaeSaL8x8Zzl3RuDKqwQIzGk7HCJ/brI283W4VpUz6JikcINHA9OobUsuiwnur7djEe3jjlslSTkhGweDmwdpdoi1ot/xyyENWhbWJO7Q9MDZIcHhoAM+IjK7quqbpLR4wUGtTodlK3XMkvgxHLkI+uvIG13FUzhGZkMHO0muZ4A9eFDAnNWVaO9ThvgSttugTYw8Pzzd8Gnjdyj781jTkogv/MzC38yB+ywYX8n/VzkvxenuL4LuxUoQDjExAOsQCd+QFmiDVyrNtGUjfW+ZiN3exG9Mx3tcHVRmzTCqRIzvmI4m3b1R/8TgcJskg/WS3pCBytT4nQwhYCDG2WX4F0tv3KVLrCvS5SXPrGAK3G6Qbo161Q8ceKMKunBJ5Aue6pZd9YimjGkRMA1mcsAd3bQlskmlUUSoVvkTQgXHCADuDz6U4okuuwc=