language: node_js
sudo: false
node_js:
- '10.16'
install:
- cd public
- npm install
script:
- npm test
before_deploy: cd ..
deploy:
  provider: firebase
  token:
    secure: E/nFclk4+XJLiISQWLMw2FMMeTVRnZRcr28OkOnQnPm8kQtXlr+1q/3l80lgPYxIOQXfGRtclh74OMrNFEkdWD/2JLRdepoU5493DAvg1MyDXnHGsuGDC54gdtI0xZdu0IAPPBlVyQde27Qapg+pxw+saWlrc5lmKqnXHt1thkvilwn3ahguk3YDUlIGHXCj+BBxJNmOXchgZ4NWrCRHpX6zjhbf1/qQ8lf220XKc5PPY4xsdGgEZCUfSyw9FU2QPqMrcOTfpDM52SiE8o9UZpJc15jaBJWI7mpammMlVvyqGuhAXXek/V+uLI8iUznyUhby08btpxyt/IMzXdExVPNiFOwIU8R68l6RfLRHk2VI3Dl56mOyJ8SzvnapuDLZEXeKbljFsdi3/OXzH2eB/YZ39cnBqYqphzQ5jRQNI74vuiLRoMssr0uold7mR0y5f6U8pP+t6SC+0yzbh7qvrkdEs5ulZsGlCqu5BqV71/SEISA0PBudbI5sSRdt++UAYDRWjOv27LkpFUBpDYc2owE6YvgdyUNt8FIQLvrxfQ4PUY6GsUcNK/atKrv6jrq06YVgTLPmZ6JfbVwKmNOEuBBbsy09xXegjWQ2penUebnBw8/4ZlpaEQ3sgjyvmSsFhqVyGEj66tI1zXstuBcGxz0VPqeYSvwTpdt5TGR+2EY=