language: node_js
sudo: false
node_js:
- '10.16'
install:
- cd public
- npm install
- gem install jekyll
- gem install jekyll-sitemap
- gem install minima
script:
- npm test
- jekyll build --trace
before_deploy: 
- ls
- cd ..
- ls
- echo $PWD
deploy:
  provider: firebase
  token:
    secure: Wrquqqg894NjrVhzdLKi77D746EWSe4dJVataEIAky5l+K6M1eJJQ1+anSROc27Atcl36sqsDvitpeNI8WJ4bW2wV/jHsXG92NaWkkoTi6jUEkvC/6X+rjf1hKvnl7iOC8URbvTiuts2MM1BUe6qy61u93dQ4Q2ulyjmVV8f9iSa4xRcTU/Ef1Qg4BHsdjWI3geQk4laivu/qe0iVRsoupoc2XRDCy87u49fM1cmGFcuzJoTibyTPZcrFgupZYA5OpRDTBbEUxOzptBMnu0JlnO4mhsLHBzvokkLIsXv6wKsBRGQCGvSJ6hC6BJMqaI33v9s3L9ZuxWi06RBe8pULfxW3JuHWr7hzKPonZqUiR5CKrpWQwG+Th1GwMhi/eVan6sB2u88CxrtCJL4PO7df5XLdYnjeAqjya7yPVSlqJeeDbCozoAtFgWgUiQRkxUWvxtW7nW3+Dot2wr+mx8mrxuYaPaImEw2Nlr1ys6sLHwX5GHvuJicWo5C0eZXpk36K5YUxIUfnd7I25gftHc2JC0MZm3gB1q2jl8aa0qCuMU81ML9b3iUC+97hM6I5C0C2XJpE7Hr+CUvZwdWYwfz98v74bIJz56tz4cYNoWzBcln+tXB6nAQrVl80ToNYgQxvAmUoqgahAdRo6keqNlWmi/qv249KkmxaD+nzsEWtMg=