language: node_js
sudo: false
node_js:
- '10.16'
install:
- cd public
- npm install
script:
- npm test
before_deploy: "cd .."
deploy:
  provider: firebase
  token:
    secure: lf5psSIBzZsJ6QVo4Vc6CYmO62QhxEKRnfMUz8c2DoflyYwWb0vbJ7vaeqwpk4CrirI0cOeNtmrufCuJ0V8KirBZFUaU2