language: node_js
sudo: false
node_js:
- '10.16'
install:
- cd public
- npm install
script:
- npm test
before_deploy: cd ..
deploy:
  provider: firebase
  token:
    secure: "CJZOFz6Uu43Xv9F9o/BDM2EL4fpYqq0xbr31aUyfE120iRH93ZYlhBzopj5AOg+z0BLP9IdB2hwC5M+vq8OKH/bxS6laaEhtex3x2oEF6sXClMVwXPkk7k8nn9zUpGmVR6XZT0uYqx8jzjY++pm64tGGh6Tju8r9K9gls1nWf5hEEVnzSAFsxDcgz3aFQ8MFMaQcm4bMyOdg8zoW1kI0FBONGq9xtPFaFS7227Sirhk+0aD5FGLgQCnqnwg1PuwbXYuXsaLS9gqGUtVLyj0Vlh/RJfV+LdSM9kzwU82yo1RPGN8tt+95uinC3/zYrIhxuomdyfk/rY/R7CouQt8/V8Bk91O1ssVdQOXHKWe7XDlQeV+/J6Tte0/lwZn263wFygDi2WwN2tfVKhJBDER/lhlpUP5+q4RuREL76K2014qtggWiT5KBJQR7V63Nm113hEfJJfMEP7g1QHZ4IZV3cJo/z5JNLTQNMrAPuVktxtpHPQsW/9CiUvdsL2/JSiH7lgdEirS6bz1Qgrpa1pu+W7EfgoLW4CTWjVGPqqAOmLcvlIURGBZGPcs8/KI8ir0oT5nXHeO7Kmys1ulbUBodTIDsU9f2hvZwuUiPUORIU6CP2NMa1q2EZOuRxSzISlhkVTGZtRDzVubj5pfNTetAXV9ASsIRQYFjo7ri4a86Ngc="